### ISSUE TITLE
 ⭐ __TS__OptionalChainAccess

### ISSUE THREAD

**Issue by websharik** [mtasa-typescript/mtasa-lua-types#49]
I was try
```javascript
let a = b.dog?.name
```
but get error:
```attepmpt to cal global '__TS__OptionalChainAccess' (a nil value)```

Upgrade your lib to last features ?
[TypeScriptToLua/src/lualib/OptionalChainAccess.ts](https://github.com/TypeScriptToLua/TypeScriptToLua/blob/d79a2078d64336188f4708fef1b5c5cd9ee64ca5/src/lualib/OptionalChainAccess.ts)

**Comment by websharik** [comment]
To lualib_bundle.lua

```lua
function __TS__OptionalChainAccess(____table, key)
    if ____table then
        return ____table[key]
    end
    return nil
end
```

**Comment by Toliak** [comment]
Yes, I will just recompile it
