### ISSUE TITLE
 ⚠️ Some functions return LuaMultiResult instead of Vector3

### ISSUE THREAD

**Issue by Dezash** [mtasa-typescript/mtasa-lua-types#60]
**Describe the bug**
Some functions such as getElementPosition, getElementRotation, getElementVelocity and getElementAngularVelocity return Vector3 when used in OOP, however in mtasa-typescript it expects LuaMultiResult<[number, number, number]>.
The same applies to setters, they should expect Vector3 as a parameter.

**To Reproduce**
```
let pos = localPlayer.position;
localPlayer.setPosition(pos.x, pos.y, pos.z + 10);
let pos2 = localPlayer.getPosition();
localPlayer.setPosition(pos2.x + 10, pos2.y, pos2.z);
```

**Expected behavior**
pos and pos2 should be of type Vector3 and have the x, y, and z properties.

**Screenshots**
![image](https://user-images.githubusercontent.com/11979849/132122749-f3dc2f2d-e5e2-43d3-a056-9635b664d879.png)

**NPM Version**
7.8.0

**NPM Package versions**
├── lua-types@2.10.1
├── mtasa-lua-types@0.4.1
├── mtasa-lua-utils@0.1.11
├── prettier@2.3.0
├── ttypescript@1.5.12
├── typescript-to-lua@0.39.3
└── typescript@4.2.4

**Additional context**
```
let pos = localPlayer.getPosition();
iprint(pos[0], pos[1], pos[2]);
```
translates into:
```
local pos = {
    localPlayer:getPosition()
}
iprint(pos[1], pos[2], pos[3])
```

prints result: `vector3: { x = 0.000, y = 0.000, z = 3.117 }    nil    nil`

**Comment by Toliak** [comment]
This issue will be fixed in 1.0.0 update

https://github.com/mtasa-typescript/mtasa-lua-types/blob/develop/server/oop/Element.d.ts#L124

https://github.com/mtasa-typescript/mtasa-lua-types/blob/develop/client/oop/Element.d.ts#L147
